name: notebook
channels:
 - pytorch
 - conda-forge
 - defaults
dependencies:
 - python=3.8*
 - pangeo-notebook=2021.02.19
 - pip=20
 - pytorch::pytorch=1.7.0=py3.8_cuda11.0.221_cudnn8.0.3_0
 - pytorch::torchvision=0.8.1
 - efficientnet-pytorch=0.6.3
 - conda-forge::openjpeg=2.4.0
 - conda-forge::sqlite=3.34.0
 - conda-forge::poppler=0.89.0
 - rasterio=1.2.1=py38h033aa8a_0
 - cudatoolkit=11.0.221
 - timm=0.3.2
 - matplotlib-base
 - adlfs>=0.5.9
 - xarray
 - jupyterlab-nvdashboard
 # https://github.com/holoviz/hvplot/issues/576
 - hvplot==0.7.0
 - datashader
 - numpy=1.19.5
 - stac-vrt
 - rioxarray
